package IntString;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 */
public class FindtheDifference389 {
    public char findTheDifference(String s, String t) {
        char[] ss = s.toCharArray();
        char[] tt = t.toCharArray();

        int result = 0;
        for(int i = 0; i < ss.length; i ++)
            result = result^ss[i];

        for(int i = 0; i < tt.length; i ++)
            result = result^tt[i];

        return (char)result;


    }
}
